#!/bin/bash
while [ $# -gt 0 ]; do
        picture=$1
		filename=$(basename "$1")
		extension="${filename##*.}"
		filename="${filename%.*}"
		for i in 1 16 22 24 32 48 64 96 128 144 196 200 256; do convert $picture -thumb "$i"\!x"$i"\! "${filename}_${i}.${extension}";done;
        shift
done

