#!/bin/bash 
#by ray anthony
#date Sept. 2014
#description: transform typical graphics file into one with a transparent background
#notes: shotgun approach works for most though different files are needed whether 
# the file is black or white (mostly) background initially.
#usage: intended for use as a nautilus shell extension this allows for context menu 
# select file or group of files, right click and bam, done. To do this for Ubuntu/Nautilus, :
#  place this file with no extension, executable and readable, in the:
# $HOME/user/.gnome2/nautilus-scripts/[this script]
# folder and name it something short so it fits nice in the right click menu. You will need to
# possibly add som# components in to automate nautilus being aware to look there try the nautilus 
# scripts package be mindful of gnome vs unity vs kde, and all that i had to add one and it gave me 
# no scripts which is when i said fuck it and had some fun making my own series
# site: http://rayanthony.io
# email: ray@rayanthony.io
# last revision: 4-13-2015
while [ $# -gt 0 ]; do
        picture="$1"
                #filenames are crazy sometimes be mindful of keeping string intact hence the quotes
                filename=$(basename "$1")
                extension="${filename##*.}"
                filename="${filename%.*}"
                #for this we dont really want the original extension lest it not permit alpha
                #convert "$picture" -transparent white -fuzz 8% "${filename}_trans.${extension}"
                convert "$picture" -transparent white -fuzz "7%" -transparent white "${filename}.png"
        shift
done
