#!/bin/bash
# sample imagemagick lines to transform icons to have a blue haze
# blucon? TEST [of rappleshot component]
# create frames with varying level of shade, other dressings, make animate, make icons for all format in sub, make starter manifest snippet, do this for each chosen file in batches or solo
# by ray anthony
while [ "$#" -gt 0 ]; do
        picture="$1"
		filename=$(basename "$1")
		extension="${filename##*.}"
		filename="${filename%.*}"
	        mkdir -p "${filename}_allsizes"
		#convert "$picture" \( +clone -background black -shadow 80x20+0+15 \) +swap -background transparent -layers merge +repage "${filename}_allsizes/{filename}_rappleshot.png"
convert "$picture" -background orange \( +clone -background lightblue -shadow 242x7+0+7 \) +swap -background transparent -layers merge -repage 512\!x512\! -resize 512\!x512\! "${filename}_allsizes/newmaster.png"
sleep 2
convert "$picture" -background orange \( +clone -background lightblue -shadow 242x7+0+7 \) +swap -background transparent -layers merge -repage 256\!x256\! -resize 256\!x256\! "${filename}_allsizes/frame1.png"
sleep 1
convert "$picture" -background orange \( +clone -background lightblue -shadow 242x8+0+8 \) +swap -background transparent -layers merge -repage 192\!x192\! -resize 192\!x192\! "${filename}_allsizes/frame2.png"
sleep 1
convert "$picture" -background orange \( +clone -background lightblue -shadow 242x9+0+9 \) +swap -background transparent -layers merge -repage 148\!x148\! -resize 148\!x148\! "${filename}_allsizes/frame3.png"
sleep 1
convert "$picture" -background orange \( +clone -background lightblue -shadow 242x10+0+10 \) +swap -background transparent -layers merge -repage 112\!x112\! -resize 112\!x112\! "${filename}_allsizes/frame4.png"
sleep 1
convert "$picture" -background orange \( +clone -background lightblue -shadow 242x11+0+11 \) +swap -background transparent -layers merge -repage 34\!x34\! -resize 34\!x34\! "${filename}_allsizes/frame5.png"
sleep 2
convert "${filename}_allsizes/frame1.png" "${filename}_allsizes/frame2.png" "${filename}_allsizes/frame3.png" "${filename}_allsizes/frame4.png" "${filename}_allsizes/frame5.png" -delay 5x1 -loop 0 "${filename}_animated-favicon.gif"
convert "$picture" -background orange \( +clone -background lightblue -shadow 242x11+0+11 \) +swap -background transparent -layers merge -repage 256\!x256\! -resize 256\!x256\! "${filename}_allsizes/icon.png"
cp "${filename}_allsizes/newmaster.png" "${filename}_allsizes/logo.png"
convert "${filename}_allsizes/newmaster.png" -repage 196\!x196\! -resize 196\!x196\! "${filename}_allsizes/favicon.png"
convert "${filename}_allsizes/icon.png" "${filename}_allsizes/favicon.ico"
convert "${filename}_allsizes/icon.png" "${filename}_allsizes/apple-touch-icon-114.png"
convert "${filename}_allsizes/logo.png" -repage 144\!x144\! -resize 144\!x144\! "${filename}_allsizes/apple-touch-icon-144.png"
cp "${filename}_allsizes/icon.png" "${filename}_allsizes/mstile-144x144.png"
		for i in 16 18 20 22 24 32 36 48 64 72 90 96 128 144 256 192 512; do convert "$picture" -resize "$i"\!x"$i"\! "${filename}_allsizes/${filename}_${i}.png";done
		for i in 57 114 72 144 60 120 76 152; do convert "$picture" -resize "$i"\!x"$i"\! "${filename}_allsizes/apple-touch-icon-${i}.png";done
                touch "${filename}_allsizes/manifest.json"
		for i in 16 18 20 22 24 32 36 48 64 72 90 96 128 144 256 192 512;do echo "\"${i}\":\"${filename}_${i}.png\"," >> "${filename}_allsizes/manifest.json";done
		#for i in 57 114 72 144 60 120 76 152;do echo "test" "${filename}_allsizes/manifest.json";done
        shift
done
